services:
  shork-486-build:
    build: .
    command:
      - --always-build
      - --is-debian
      - --target-disk=100
      - --target-swap=8
      - --fix-extlinux
      - --enable-gui
      #- --skip-busybox
    environment:
      - HOST_GID=1000
      - HOST_UID=1000
      - IN_DOCKER=1
    privileged: true
    volumes:
      - ./shork-486:/var/shork-486
