services:
  shork486-build:
    build: .
    command:
      - --always-build
      - --is-debian
      - --target-disk=75
      - --target-swap=16
    environment:
      - HOST_GID=1000
      - HOST_UID=1000
      - IN_DOCKER=1
    privileged: true
    volumes:
      - ./shork486:/var/shork486
