services:
  shork486-build:
    build: .
    command:
      - --always-build
      - --is-debian
      - --minimal
    environment:
      - HOST_GID=1000
      - HOST_UID=1000
    privileged: true
    volumes:
      - ./shork486:/var/shork486
